### ISSUE TITLE
0.47版 NullPointerException 

### ISSUE THREAD

**Issue by l736192959** [wanglu1209/PhotoViewer#14]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable com.wanglu.photoviewerlibrary.photoview.PhotoView.getDrawable()' on a null object reference
at com.wanglu.photoviewerlibrary.PhotoViewerFragment$onLazyLoad$2.run(PhotoViewerFragment.kt:53)
at java.lang.Thread.run(Thread.java:818)

**Comment by wanglu1209** [comment]
你好，具体是什么操作触发的

**Comment by jccppp** [comment]
我也遇到了,是网络不行点击了图片,后续会出现这个
