### ISSUE TITLE
图片放到最大 点击返回会闪退

### ISSUE THREAD

**Issue by SilasDong** [wanglu1209/PhotoViewer#8]
11-23 19:14:56.873 4148-4148/com.bk.spay E/MessageQueue-JNI: java.lang.IllegalArgumentException: Scale must be within the range of minScale and maxScale
        at com.wanglu.photoviewerlibrary.photoview.PhotoViewAttacher.setScale(PhotoViewAttacher.java:543)
        at com.wanglu.photoviewerlibrary.photoview.PhotoViewAttacher.setScale(PhotoViewAttacher.java:533)
        at com.wanglu.photoviewerlibrary.photoview.PhotoViewAttacher.setScale(PhotoViewAttacher.java:529)
        at com.wanglu.photoviewerlibrary.photoview.PhotoView.setScale(PhotoView.java:380)
        at android.animation.PropertyValuesHolder.nCallFloatMethod(Native Method)
        at android.animation.PropertyValuesHolder.-wrap4(Unknown Source:0)
        at android.animation.PropertyValuesHolder$FloatPropertyValuesHolder.setAnimatedValue(PropertyValuesHolder.java:1387)
        at android.animation.ObjectAnimator.animateValue(ObjectAnimator.java:990)
        at android.animation.ValueAnimator.setCurrentFraction(ValueAnimator.java:654)
        at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:617)
        at android.animation.ValueAnimator.start(ValueAnimator.java:1046)
        at android.animation.ValueAnimator.start(ValueAnimator.java:1065)
        at android.animation.ObjectAnimator.start(ObjectAnimator.java:852)
        at android.animation.ValueAnimator.startWithoutPulsing(ValueAnimator.java:1058)
        at android.animation.AnimatorSet.handleAnimationEvents(AnimatorSet.java:1142)
        at android.animation.AnimatorSet.startAnimation(AnimatorSet.java:1227)
        at android.animation.AnimatorSet.start(AnimatorSet.java:729)
        at android.animation.AnimatorSet.start(AnimatorSet.java:684)
        at com.wanglu.photoviewerlibrary.photoview.PhotoView.exit(PhotoView.java:172)
        at com.wanglu.photoviewerlibrary.PhotoViewerFragment$onLazyLoad$6.onKey(PhotoViewerFragment.kt:98)
        at android.view.View.dispatchKeyEvent(View.java:11749)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1832)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1843)
        at android.support.v4.view.ViewPager.dispatchKeyEvent(ViewPager.java:2761)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1843)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1843)
        at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:558)
        at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1967)
        at android.app.Activity.dispatchKeyEvent(Activity.java:3350)
        at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:541)
        at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:319)
        at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:452)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4906)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4767)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4269)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4339)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4297)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4439)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4305)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4496)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4269)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4339)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4297)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4305)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4269)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4339)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4297)
    	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImp

**Comment by SilasDong** [comment]
我把 throw new IllegalArgumentException("Scale must be within the range of minScale and maxScale"); 给注释了 就可以了 不知道有没有其他的影响

**Comment by wanglu1209** [comment]
没影响，我也删了。我一会儿重新发个包，上个问题我正在改
